version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=first_db
      - DATABASE_USER=user
      - DATABASE_PASSWORD=Test123
    volumes:
      - .html/:/var/www/html
      - db_data:/var/lib/mysql
    depends_on:
      - db
    networks:
      custom_network:
        ipv4_address: 10.2.100.22

  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: first_db
      MYSQL_USER: user
      MYSQL_PASSWORD: Test123
      MYSQL_ROOT_PASSWORD: Test123
    volumes:
      - db_data:/var/lib/mysql
    networks:
      custom_network:
        ipv4_address: 10.2.100.23

volumes:
  db_data: {}

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.2.0.0/16
